[AVS-288] Update the video encoder abstraction
sportsball-ai/av-rs pull request #102
Opened 2022-07-19 21:39 UTC by lzuosym

This adds a new parameter `EncodedFrameType` to `VideoEncoder::encode` API to allows users to explicitly specify encoded frame types for libx264 or Video Toolbox.

1. For x264 encoder, there is a direct mapping from `EncodedFrameType` to properties defined in x264
2. For Video Toolbox, [`kVTEncodeFrameOptionKey_ForceKeyFrame`](https://developer.apple.com/documentation/videotoolbox/kvtencodeframeoptionkey_forcekeyframe) property seems to be used to force the current encoded frame to be a key frame. But there is not corresponding types for `Auto` and `Predicted`.

2022-07-19 22:28 UTC, lzuosym commented on macos/video-toolbox/src/compression_session.rs
> +                        d.cf_type_ref()
@ccbrown there seems to be something wrong here, which fails the unit test for VideoToolbox encoder, but I couldn't figure it out, can you please take a look?

2022-07-19 23:49 UTC, ccbrown commented on macos/video-toolbox/src/compression_session.rs
> +                };
The dictionary was being freed before the `VTCompressionSessionEncodeFrame` call, resulting in a crash. I refactored things a bit to make this work.

2022-07-20 00:00 UTC, ccbrown requested changes
I went ahead and update the xcoder crates too. Let's remove `Predicted` for now though. Otherwise this lgtm.

2022-07-20 00:01 UTC, lzuosym commented on macos/video-toolbox/src/compression_session.rs
> +                };
That makes sense! 👍

2022-07-20 00:33 UTC, ccbrown approved these changes

2022-07-20 00:35 UTC, merged