fix SRT async write
sportsball-ai/av-rs pull request #153
Opened 2023-03-03 23:18 UTC by lzuosym

2023-03-03 23:54 UTC, scottlamb requested changes
I think we should match this in the synchronous write path used by the agent. Do you want to do that in the same PR or different?

https://github.com/sportsball-ai/av-rs/blob/e169574a6720928cc9ab67862a69975a8b450508/srt/src/lib.rs#L532

2023-03-03 23:54 UTC, scottlamb commented on srt/src/async_lib.rs
> +        assert_eq!(client_conn.payload_size(), 1316);
Maybe grow the payload on 285 to exercise the changes?

2023-03-03 23:54 UTC, scottlamb commented on srt/src/async_lib.rs
> +        while sent < src.len() {
Isn't this loop producing small writes any time `src.len() % self.payload_size != 0`?

I don't think we need to loop. `tokio::io::AsyncWrite::poll_write` (like `std::io::Write::write`) is allowed to write only part of the bytes. If it's wrapped in a buffered writer with a buffer size >= `self.payload_size`, then we'll only produce small writes on flush, which is as it should be.

[`std::io::Write::write`](https://doc.rust-lang.org/std/io/trait.Write.html#tymethod.write) actually forbids looping:

> A call to write represents *at most one* attempt to write to any wrapped object.

2023-03-04 04:40 UTC, lzuosym commented
> I think we should match this in the synchronous write path used by the agent. Do you want to do that in the same PR or different?
> 
> https://github.com/sportsball-ai/av-rs/blob/e169574a6720928cc9ab67862a69975a8b450508/srt/src/lib.rs#L532

I can do it here.

2023-03-04 04:48 UTC, lzuosym commented on srt/src/async_lib.rs
> +        while sent < src.len() {
It's actually wrong to use a loop to send data async. If `Pending` returns from inside the loop, runtime will re-write the all data from beginning.

2023-03-06 19:06 UTC, scottlamb approved these changes

2023-03-06 20:52 UTC, ccbrown commented on srt/src/lib.rs
> +            let max_send_payload_size = options.max_send_payload_size.unwrap_or(DEFAULT_SEND_PAYLOAD_SIZE as _) as _;
Would it make sense if instead of doing this, we checked `SRT_SOCKOPT_SRTO_PAYLOADSIZE` after the call to `srt_connect`?

And should we really default to `DEFAULT_SEND_PAYLOAD_SIZE`? Why not default to the previous behavior of not having a limit? Maybe that depends on in what circumstances `SRT_SOCKOPT_SRTO_PAYLOADSIZE` doesn't have a value?

2023-03-06 22:05 UTC, lzuosym commented on srt/src/lib.rs
> +            let max_send_payload_size = options.max_send_payload_size.unwrap_or(DEFAULT_SEND_PAYLOAD_SIZE as _) as _;
> Would it make sense if instead of doing this, we checked `SRT_SOCKOPT_SRTO_PAYLOADSIZE` after the call to `srt_connect`?

Agree, this can be moved after the call to `srt_connect`.

> And should we really default to `DEFAULT_SEND_PAYLOAD_SIZE`? Why not default to the previous behavior of not having a limit? Maybe that depends on in what circumstances `SRT_SOCKOPT_SRTO_PAYLOADSIZE` doesn't have a value?

Even if `SRT_SOCKOPT_SRTO_PAYLOADSIZE` is not set, `socket.get::<i32>(sys::SRT_SOCKOPT_SRTO_PAYLOADSIZE)` will always have some value (1316 default) . So yes, it's not necessary to define a `DEFAULT_SEND_PAYLOAD_SIZE` const.

2023-03-06 23:18 UTC, ccbrown commented on srt/src/async_lib.rs
> +        let data_size = self.max_send_payload_size.min(src.len());
A `0` value for `SRTO_PAYLOADSIZE` has a special meaning:

> When set to 0, there's no limit for a single sending call.

– https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md#SRTO_PAYLOADSIZE

So maybe the logic should be something like...

```suggestion
        let data_size = if self.max_send_payload_size != 0 { self.max_send_payload_size.min(src.len()) } else { src.len() };
```

?

2023-03-07 15:16 UTC, ccbrown approved these changes

2023-03-07 15:52 UTC, merged