[AVS-861] reset stream metadata for each new segment
sportsball-ai/av-rs pull request #159
Opened 2023-05-25 18:00 UTC by lzuosym

2023-05-25 18:03 UTC, scottlamb requested changes
Needs a test.

2023-05-25 22:31 UTC, scottlamb commented on mpegts-segmenter/src/segmenter.rs
> +            match &segments[0].1.streams[0] {
`segments[0]`?

If I comment out the `self.analyzer.reset_stream_metadata();` on line 213, the test still passes, so it's not testing the right thing.

2023-05-25 22:46 UTC, lzuosym commented on mpegts-segmenter/src/segmenter.rs
> +            match &segments[0].1.streams[0] {
fixed it.

2023-05-25 22:57 UTC, scottlamb commented on mpegts-segmenter/src/segmenter.rs
> +                        assert!(ptses[i] > ptses[i - 1]);
Every frame in this file has private data. I'd also do `assert_eq!(ptses[0], 0);` and it fails. I don't think the pts reference is being reset correctly.

2023-05-25 22:59 UTC, scottlamb commented on mpegts-segmenter/src/segmenter.rs
> +        for i in 0..3 {
btw, I'd just do `for seg in &segments` and then `match &seg.1.streams[0]`. More readable, harder to make the `[i]`->`[0]` mistake.

2023-05-25 23:36 UTC, lzuosym commented on mpegts-segmenter/src/segmenter.rs
> +                        assert!(ptses[i] > ptses[i - 1]);
Good point!

2023-05-25 23:37 UTC, lzuosym commented on mpegts-segmenter/src/segmenter.rs
> +        for i in 0..3 {
done

2023-05-26 00:14 UTC, scottlamb approved these changes

2023-05-26 00:26 UTC, merged