[AVS-1020] Update to v2 allocation and reservation functions
sportsball-ai/av-rs pull request #176
Opened 2023-11-20 18:35 UTC by epingel2

This updates to the "v2" allocation and reservation functions and structures present in xilinx 3.0 These are the structures and functions used by xilinx's ffmpeg and some of their example code. They allow a reduction in some code duplication and a more accurate allocation and reservation of resources based both on device Id as well as reservation id

2023-11-20 20:09 UTC, scottlamb requested changes

2023-11-20 20:09 UTC, scottlamb commented on xilinx/src/xlnx_dec_utils.rs
> +fn xlnx_fill_dec_pool_props(cu_pool_prop: &mut xrmCuPoolPropertyV2, dec_load: i32, device_id: Option<u64>) -> Result<(), SimpleError> {
Maybe `Option<u32>`, given that the header says `#define XRM_DEVICE_INFO_DEVICE_INDEX_MASK 0xFFFFFFFF`? Giving a `device_id` larger than a `u32` would overflow into the other parts of the `device_info` and go poorly.

There's an argument to be made that they might change these constants (so we should use an `u64` and check the mask) but given that they've added comments to the header with specific bit positions and such I don't think they would do that without changing to a `v3`.

2023-11-20 20:09 UTC, scottlamb commented on xilinx/src/xlnx_dec_utils.rs
> +    cu_pool_prop.cuListProp.cuProps[0].deviceInfo = device_info as _;
`as _` seems unnecessary/hazardous here? If `device_info` isn't already 64-bit, I don't think the shifts above will work out well.

2023-11-20 20:09 UTC, scottlamb commented on xilinx/src/xlnx_scal_utils.rs
> +            // use the zero indexed device as the default if no device or reserve_id have been provided
This seems like a surprising behavior. Is it necessary, or can we leave `deviceInfo` at `0`?

2023-11-22 17:53 UTC, scottlamb requested changes

2023-11-22 17:53 UTC, scottlamb commented on xilinx/src/xlnx_dec_utils.rs
> +    pub cu_list_res: xrmCuListResourceV2,
As we discovered together yesterday: `xrmCuListPropertyV2` is enormous so needs to be boxed to avoid stack overflows. Lemme know when that's ready for review.

2023-11-22 18:38 UTC, epingel2 commented on xilinx/src/xlnx_dec_utils.rs
> +    pub cu_list_res: xrmCuListResourceV2,
These are now all boxed.

2023-11-22 18:47 UTC, scottlamb approved these changes

2023-11-22 19:17 UTC, merged