add v4l2 crate
sportsball-ai/av-rs pull request #185
Opened 2024-04-06 19:31 UTC by ccbrown

2024-04-06 19:50 UTC, ccbrown commented on .github/workflows/rust.yml
> +      fail-fast: false
Any opposition to this? Before, if the macOS build failed in CI, the Ubuntu build would immediately be cancelled. When one build fails, I would prefer to see the other continue so I can comprehensively see where the failures are/aren't.

2024-04-08 04:18 UTC, Xaeroxe requested changes
Neat! Thanks for implementing this. I've added a few minor comments below.

2024-04-08 04:18 UTC, Xaeroxe commented on v4l2/src/encoder.rs
> +            Self::Bgra => 0x34524742,
We should create constants for these hexadecimal literals that have a meaningful and descriptive name. Additionally we should note that these constants are in fourcc format. `H264_PIXELFORMAT` a few lines below is a great example of this.

2024-04-08 04:18 UTC, Xaeroxe commented on .github/workflows/rust.yml
> +      fail-fast: false
Seems fine to me.

2024-04-08 04:18 UTC, Xaeroxe commented on v4l2/src/encoder.rs
> +            .collect::<Result<Vec<_>>>()?;
Since we have a few constant size `Vec` in here, consider turning them into arrays and using [`array::from_fn`](https://doc.rust-lang.org/std/array/fn.from_fn.html) in order to simplify usage for the CPU and the dev. 

For the `Drop` impl, you would then need to wrap these inside of a [`ManuallyDrop`](https://doc.rust-lang.org/std/mem/struct.ManuallyDrop.html). This technically adds more `unsafe`, but I think that's desirable seeing as we're opinionated about the drop order anyways.

If you really don't like `ManuallyDrop`, another option is [`ArrayVec`](https://docs.rs/tinyvec/1.6.0/tinyvec/struct.ArrayVec.html).

2024-04-08 04:18 UTC, Xaeroxe commented on .github/workflows/rust.yml
> +      fail-fast: false
Seems fine to me.

2024-04-08 04:37 UTC, Xaeroxe commented on v4l2/src/encoder.rs
> +    available_capture_buffers: Vec<usize>,
These might be a good opportunity for an [`ArrayVec`](https://docs.rs/tinyvec/latest/tinyvec/struct.ArrayVec.html)

2024-04-08 09:42 UTC, ccbrown commented on v4l2/src/encoder.rs
> +            let output_parm = unsafe { &mut parm.parm.output };
We're reading a union field here, which is always unsafe.

2024-04-08 10:22 UTC, ccbrown commented on v4l2/src/encoder.rs
> +            .collect::<Result<Vec<_>>>()?;
`tinyvec::ArrayVec` can't be used here since `PlaneMapping` doesn't implement `Default`. An array feels a little messier here as there's currently not a great way to initialize one from fallible operations ([try_map](https://doc.rust-lang.org/std/primitive.array.html#method.try_map) will help here once stable).

Instead, I went with [`arrayvec::ArrayVec`](https://docs.rs/arrayvec/0.7.4/arrayvec/struct.ArrayVec.html) both here and for `available_xxx_buffers`. Let me know how that looks to you.

2024-04-08 10:24 UTC, ccbrown commented on v4l2/src/encoder.rs
> +            Self::Bgra => 0x34524742,
`const BGRA = 0x34524742`, `Self::Bgra => BGRA` seemed a little superfluous to me. I added comments indicating that these are four-character codes and what their values are. How's that?

2024-04-08 14:05 UTC, Xaeroxe commented on v4l2/src/encoder.rs
> +            let output_parm = unsafe { &mut parm.parm.output };
Thank you

2024-04-08 14:06 UTC, Xaeroxe commented on v4l2/src/encoder.rs
> +            Self::Bgra => 0x34524742,
That's a lot better. Thanks!

2024-04-08 14:07 UTC, Xaeroxe commented on v4l2/src/encoder.rs
> +            .collect::<Result<Vec<_>>>()?;
Excellent! Looks great.

2024-04-08 14:07 UTC, Xaeroxe commented on v4l2/Cargo.toml
> +v4l2r = { git = "https://github.com/Gnurou/v4l2r", rev = "6091b1f0643f20435b97413635d935052f19c739" }
@ccbrown This is the only comment of mine that's outstanding now

2024-04-08 17:04 UTC, ccbrown commented on v4l2/Cargo.toml
> +v4l2r = { git = "https://github.com/Gnurou/v4l2r", rev = "6091b1f0643f20435b97413635d935052f19c739" }
I agree, but I'd propose we consider that beyond the scope of this PR as it applies to many (or all?) of our other third party dependencies.

2024-04-08 17:06 UTC, Xaeroxe commented on v4l2/Cargo.toml
> +v4l2r = { git = "https://github.com/Gnurou/v4l2r", rev = "6091b1f0643f20435b97413635d935052f19c739" }
Sure, I'll add a ticket for it to the backlog.

2024-04-08 17:14 UTC, Xaeroxe approved these changes

2024-04-08 20:53 UTC, merged