Timecodes
sportsball-ai/av-rs pull request #28
Opened 2020-10-19 17:15 UTC by dotcypress

2020-10-23 18:35 UTC, ccbrown requested changes

2020-10-23 18:35 UTC, ccbrown commented on h264/src/sequence_parameter_set.rs
> +    pub vcl_hrd_parameters: Option<HRDParameters>,
For all of the other structs and fields, I've been keeping them in order and commented with their conditionals, making them read as closely as possible as they do in the spec. See the other fields in the same struct for example. These look like they're out of order and missing comments.

2020-10-23 18:35 UTC, ccbrown commented on utils/Cargo.toml
> +[package]
This package looks unintentional.

2020-10-23 18:35 UTC, ccbrown commented on h264/src/lib.rs
> +pub fn read_first_sei_pic_timing<T: Read>(reader: T) -> io::Result<PicTiming> {
This is extremely niche. It only works for annex B, only works when you don't care about anything else in the bitstream, only works when you don't care about subsequent timecodes, only works when there's an SPS NALU present before the first SEI, etc. And reading through the entire stream again just for that one bit of information is far from zero-cost.

I'm thinking that this is better done elsewhere. For example, the analyzer in mpegts-segmenter can do this more efficiently and output it in its `StreamInfo` for the video.

2020-10-23 22:34 UTC, ccbrown requested changes
I think there's quite a bit missing here. We need to support the full timecode, including frame number. Only decoding the seconds isn't enough. Furthermore, we need to properly support pic_timing messages that don't contain hours / minutes / seconds.

2020-10-23 22:34 UTC, ccbrown commented on h264/src/sei.rs
> +}
I've been trying to keep the naming consistent with the spec. Can we name this `SEIMessage`?

2020-10-23 22:34 UTC, ccbrown commented on h264/src/sei.rs
> +  pub seconds: u8,
How does a user of this library know if hours, minutes, or seconds are even present? Can we add the fields for sub-second timecodes like the frame count?

2020-10-23 22:34 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +                timing: pic_timing.as_ref().map(|timing| StreamTiming {
Let's name this field "timecode" instead of "timing" to be more specific. I'll be adding other timing-related fields soon.

2020-10-23 22:38 UTC, dotcypress commented on h264/src/sei.rs
> +}
Yep, will do

2020-10-27 00:22 UTC, ccbrown commented on h264/src/sei.rs
> +  pub frames: Option<u8>,
Is there a reason we shouldn't have the other fields here? The rest of this library aims to be an unopinionated transliteration of the spec, but this `PicTiming` struct is something that differs radically from what's in the spec. In addition to omitting a lot of relevant fields, it doesn't have well-defined behavior when `NumClockTS` isn't 1 (all of these things should be in a `Vec`).

2020-10-27 00:30 UTC, ccbrown requested changes

2020-10-27 00:30 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +    pub frames: Option<u8>,
Why are all of these `Option`s? We should either have the timecode or not have the timecode. That means you need to implement logic for...

> When hours_value is not present, the previous hours_value in decoding order shall be used as hH to compute clockTimestamp.

> When minutes_value is not present, the previous minutes_value in decoding order shall be used as mM to compute clockTimestamp.

> When seconds_value is not present, the previous seconds_value in decoding order shall be used as sS to compute clockTimestamp.

2020-10-27 16:38 UTC, dotcypress commented on mpegts-segmenter/src/analyzer.rs
> +    pub frames: Option<u8>,
Fixed

2020-10-27 17:24 UTC, ccbrown requested changes

2020-10-27 17:24 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +        timecodes: Vec<StreamTimecode>,
I think this could use a comment explaining why it's a `Vec` and what it means for it to contain multiple timecodes.

2020-10-27 17:24 UTC, ccbrown commented on h264/src/sei.rs
> +  pub seconds: u8,
Looks like the first question here got unresolved:

> How does a user of this library know if hours, minutes, or seconds are even present?

If the first pic_timing message we see is missing hours, we don't have a complete timecode. How does a user of this library distinguish missing hours from 0 hours?

Again, the structs in this library should be as unopinionated as possible. We shouldn't make any assumptions about what fields the user of this library will need or what they're doing with them.

Rather than parsing everything and discarding the fields we don't think users will need, I'd prefer if we literally just copied / pasted the spec here. I.e. this struct should have fields named `ct_type`, `nuit_field_based_flag`, `counting_type`, `full_timestamp_flag`, `discontinuity_flag`, `cnt_dropped_flag`, `n_frames`, `seconds_value`, `minutes_value`, etc.

2020-10-27 20:01 UTC, ccbrown requested changes

2020-10-27 20:01 UTC, ccbrown commented on h264/src/sei.rs
> +      }
> When the time_offset_length syntax element is not present, it shall be inferred to be equal to 24.

2020-10-27 20:01 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +        // One timecode per each ClockTS
I meant at a slightly higher level. Let's not make users of this struct dig through the H264 spec to figure out when there might be more than one clock timestamp and what each one means.

2020-10-27 20:06 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +                        frames: t.n_frames.0,
Where did the logic go for the fallbacks like:

> When minutes_value is not present, the previous minutes_value in decoding order shall be used as mM to compute clockTimestamp.

?

2020-10-28 00:27 UTC, ccbrown commented on mpegts-segmenter/src/segmenter.rs
> +                            timecodes: timecodes.clone(),
It looks like you're using timecodes from the end of the segment here? I think it would be a lot more useful if we had timecodes from the beginning of the segment. E.g. a 3-second segment that starts at 00:05:00.00 should have a timecode of 00:05:00.00 rather than 00:08:00.00.

2020-10-29 15:54 UTC, dotcypress commented on mpegts-segmenter/src/segmenter.rs
> +                            timecodes: timecodes.clone(),
Now all timecodes from are available

2020-10-29 17:57 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +                                    timecodes.push(pic_timing);
If every frame in a 5 hour 29.97 FPS stream has a timecode, there will be 539,460 elements in `timecodes` by the end. Keeping every one of those in memory seems a little excessive.

2020-10-29 17:57 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +                timecodes: timecodes.iter().filter_map(|t| t.timecodes.iter().next()).fold(vec![], |mut acc, t| {
What's happening here? Why are we just taking the first timecode from each `PicTiming` message?

2020-10-29 17:57 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +                    ],
Is this actually the expected output? At a glance, it looks like there's an SEI message after every access unit delimiter. Why is there only one timecode per second?

2020-10-30 03:12 UTC, ccbrown requested changes
Looks great! Just needs tests!

2020-10-30 20:27 UTC, ccbrown approved these changes

2020-10-30 21:59 UTC, merged