Extract first timecode
sportsball-ai/av-rs pull request #31
Opened 2020-11-02 17:13 UTC by dotcypress

Extract the first timecode from video stream.

2020-11-02 21:42 UTC, ccbrown requested changes
I don't think this is quite right. Let's do some TDD: Can you add a test for the segmenter to take a file with timecodes, segment it, then ensure that each segment has the expected timecode?

2020-11-04 22:11 UTC, ccbrown requested changes

2020-11-04 22:11 UTC, ccbrown commented on mpegts-segmenter/src/segmenter.rs
> +                }
Please double check these. We want the timecode of the first frame in each segment when possible.

2020-11-05 20:09 UTC, ccbrown commented on mpegts-segmenter/src/segmenter.rs
> +                self.analyzer.reset_timecodes();
I feel like we should be able to do this without this `reset_timecodes` mechanism. At this point, the segmenter has normally just written the first keyframe of the segment to the analyzer. So if the analyzer tracks the last timecode scene, we should be able to use that as the segment's timecode. Right?

The behavior of timecode in the analyzer just seems a bit weird to me.

2020-11-05 20:11 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +                                                    timecode.hours = previous_timecode.hours;
Can we find or make a video that exercises this code? My interpretation of the spec was that we should use the previous timecode's values, even if the previous timecode was for a previous access unit (i.e. not in the same SEI).

2020-11-05 23:26 UTC, ccbrown requested changes
Okay, I still think this is doable without the resetting, but that's no big deal. This structure is just fine as long as we make sure it works properly.

Right now I don't believe it works properly for access units that don't also have SPSs (non-keyframes usually). I think everything else about it works fine, but as this is clearly tricky to get right, I'd really like to create some tests that 1. would confirm or disprove the above bug theory and 2. exercise the code for pic timing messages with full_timestamp_flag = 0.

2020-11-05 23:26 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +pub struct StreamTimecode {
Could probably simplify to just `Timecode` especially since this will be used outside of the context of `Stream`.

2020-11-05 23:26 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +                            if let Some(vui_params) = &last_vui_parameters {
As far as I can tell, `last_vui_parameters` is only `Some` when there was an SPS within the same access unit. Are SEI messages just ignored for non-keyframes?

2020-11-05 23:26 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +                *timecode_pending = true;
Could probably just set `timecode` to `None` and get rid of `timecode_pending`.

2020-11-05 23:43 UTC, dotcypress commented on mpegts-segmenter/src/analyzer.rs
> +                *timecode_pending = true;
But I need to store latest timecode in case current one has `full_timestamp_flag == 0`

2020-11-05 23:50 UTC, dotcypress commented on mpegts-segmenter/src/analyzer.rs
> +                            if let Some(vui_params) = &last_vui_parameters {
Yes, this is a bug. 
Fixed

2020-11-05 23:51 UTC, dotcypress commented on mpegts-segmenter/src/analyzer.rs
> +pub struct StreamTimecode {
Agreed!

2020-11-06 00:02 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +                *timecode_pending = true;
You're using `last_timecode` for that, which `timecode_pending` has no impact on.

2020-11-06 00:10 UTC, dotcypress commented on mpegts-segmenter/src/analyzer.rs
> +                *timecode_pending = true;
Fixed!

2020-11-06 00:16 UTC, ccbrown commented
Yeah I think this looks good, but I do want to spend some time tomorrow looking at it more closely and trying to find some more test data.

2020-11-06 23:33 UTC, ccbrown commented
If you go here, a lot of the samples use full_timestamp_flag = 0:

https://www.mainconcept.com/us/getting-started/samples.html

You can use this one for example: http://downloads.mainconcept.com/MainConceptLogo_Blu-ray_AVC_1920x1080_LPCM.zip

Just use FFmpeg to convert / trim to a small .ts file we can commit.

2020-11-06 23:38 UTC, ccbrown requested changes

2020-11-06 23:38 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +                                        if let Some(previous_timecode) = acc.iter().last() {
Isn't `acc` a `Vec`? Can't you just use `.last()` without iterating again?

```suggestion
                                        if let Some(previous_timecode) = acc.last() {
```

2020-11-06 23:38 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +                                        h264::PicTiming::decode(&mut bs, &vui_params).unwrap().timecodes
🚨 🚓 🚨 `unwrap` isn't okay here.

2020-11-06 23:40 UTC, ccbrown commented on mpegts-segmenter/src/analyzer.rs
> +                                        let mut bs = h264::Bitstream::new(sei_message.payload.iter().copied());
I think we can move out of sei_message here to simplify things:

```suggestion
                                    .sei_message
                                    .into_iter()
                                    .flat_map(|sei_message| {
                                        let mut bs = h264::Bitstream::new(sei_message.payload);
```

2020-11-07 00:21 UTC, dotcypress commented on mpegts-segmenter/src/analyzer.rs
> +                                        h264::PicTiming::decode(&mut bs, &vui_params).unwrap().timecodes
Oops!
Fixed

2020-11-07 00:23 UTC, dotcypress commented
> If you go here, a lot of the samples use full_timestamp_flag = 0:
> 
> https://www.mainconcept.com/us/getting-started/samples.html
> 
> You can use this one for example: http://downloads.mainconcept.com/MainConceptLogo_Blu-ray_AVC_1920x1080_LPCM.zip
> 
> Just use FFmpeg to convert / trim to a small .ts file we can commit.

New test added with video trimmed from 00:00:05 to 00:00:10, and resulting timecodes looks goods.

2020-11-07 00:29 UTC, ccbrown commented on h264/src/sei.rs
> +        let hrd_params = vui_params.nal_hrd_parameters.as_ref().or_else(||vui_params.vcl_hrd_parameters.as_ref());
What's this change for?

2020-11-07 00:30 UTC, dotcypress commented on h264/src/sei.rs
> +        let hrd_params = vui_params.nal_hrd_parameters.as_ref().or_else(||vui_params.vcl_hrd_parameters.as_ref());
To disable Clippy warning

2020-11-07 00:38 UTC, ccbrown approved these changes

2020-11-07 00:40 UTC, merged