AVS-211 add wall-clock timestamps to video streams
sportsball-ai/av-rs pull request #86
Opened 2022-05-10 14:56 UTC by lzuosym

Currently, the AV service timestamps video based on when that video is received, which makes the timestamps subject to network and other types of upstream jitter.

This PR makes it possible for av-agent to embed accurate wall-clock timestamps in TS packets.

For context, see the paper [Understanding Timelines within MPEG Standards](https://ieeexplore.ieee.org/document/7293587) and ISO/IEC 13818-1:2019(E) Annex U `Carriage of timeline and external media information (TEMI) over MPEG-2 transport streams`

2022-05-10 17:27 UTC, dotcypress commented on mpeg2/src/temi.rs
> +            buf[5] = self.timescale as _;
I think we can this code more readable with something like `BigEndian::read_u32(&mut buf[5..8), self.timescale)`. And `BigEndian::read_u32(&buf)` to converting back.

2022-05-10 17:48 UTC, lzuosym commented on mpeg2/src/temi.rs
> +            buf[5] = self.timescale as _;
I was supposed to add Edward to review PR. Sorry for getting you involved. Thanks for reviewing the code! Is `BigEndian` from `byteorder` crate?

2022-05-10 17:50 UTC, dotcypress commented on mpeg2/src/temi.rs
> +            buf[5] = self.timescale as _;
Yes, BigEndian from byteorder crate.

2022-05-10 17:51 UTC, lzuosym commented on mpeg2/src/temi.rs
> +            buf[5] = self.timescale as _;
👍

2022-05-10 19:02 UTC, ccbrown commented on mpeg2/src/temi.rs
> +        }
Shouldn't this be...

```suggestion
        if self.force_reload.unwrap_or(false) {
            buf[2] |= 0b0010_0000;
        }
        if self.paused.unwrap_or(false) {
            buf[2] |= 0b0100_0000;
        }
        if self.discontinuity.unwrap_or(false) {
            buf[3] = 0b1000_0000;
        }
```

?

2022-05-10 19:11 UTC, ccbrown commented on mpeg2/src/temi.rs
> +        } else if let Some(ptp_ts) = self.ptp_timestamp {
I don't see any reason we couldn't have both of these:

```suggestion
        }

        if let Some(ptp_ts) = self.ptp_timestamp {
```

2022-05-10 19:18 UTC, lzuosym commented on mpeg2/src/temi.rs
> +        }
![image](https://user-images.githubusercontent.com/13324159/167704999-b59bed36-bf7c-4dbc-9738-c853fa55587c.png)
I think `paused` is the lowest-order bit in `buf[2]`.

2022-05-10 19:18 UTC, ccbrown commented on mpeg2/src/temi.rs
> +    pub media_timestamp: u64,
It seems like you could get rid of this field. You could instead make `media_timestamp` an `Option<u64>`, and during encoding, say:

```rust
let has_timestamp = media_timestamp.map(|ts| if ts >> 32 != 0 { 2 } else { 1 }).unwrap_or(0);
```

2022-05-10 19:19 UTC, lzuosym commented on mpeg2/src/temi.rs
> +        } else if let Some(ptp_ts) = self.ptp_timestamp {
should be able to have both! 👍

2022-05-10 19:19 UTC, ccbrown commented on mpeg2/src/temi.rs
> +    pub discontinuity: Option<bool>,
Why not just make these `bool`s?

```suggestion
    pub force_reload: bool,
    pub paused: bool,
    pub discontinuity: bool,
```

2022-05-10 19:22 UTC, ccbrown commented on mpeg2/src/temi.rs
> +        }
Ah, you're right. I read that wrong. 👍

2022-05-10 19:32 UTC, lzuosym commented on mpeg2/src/temi.rs
> +    pub discontinuity: Option<bool>,
I don't see any reason to use `bool` instead of `Option<bool>`.  Encoded `None` valued won't be decoded to `None`.    Will remove `Option`.

2022-05-10 20:58 UTC, ccbrown commented on mpeg2/src/ts.rs
> +    pub temi_timeline_descriptor: Option<TEMITimelineDescriptor>,
As far as I can tell, an adaptation field can have multiple timeline descriptors. Should this be a `Vec` instead of `Option`?

2022-05-10 21:31 UTC, lzuosym commented on mpeg2/src/ts.rs
> +    pub temi_timeline_descriptor: Option<TEMITimelineDescriptor>,
you are right, the standards support multiple timeline descriptors. But in reality do we need to embed more than 2 TEMITimelineDescriptors with different timestamps in one TS packet? I though we might need `Vec` for different types of TEMI descriptors. For simplicity purposes, only one timeline descriptor is in here.

2022-05-10 21:34 UTC, ccbrown commented on mpeg2/src/ts.rs
> +    pub temi_timeline_descriptor: Option<TEMITimelineDescriptor>,
We might not have any current use-cases for multiple timeline descriptors, but I'd like to keep this crate as unopinionated and as close to the spec as possible.

2022-05-10 22:51 UTC, lzuosym commented on mpeg2/src/ts.rs
> +    pub temi_timeline_descriptor: Option<TEMITimelineDescriptor>,
sure, shouldn't be a problem to make it `Vec`.

2022-05-11 00:59 UTC, lzuosym commented on mpeg2/src/temi.rs
> +    pub media_timestamp: u64,
This seems to be wrong. When I decode a packet from a real video clip. `has_timestamp=2`, but `media_timestamp` is `0`.  It is the value of `has_timestamp` that determines the presence of `media_timestamp` and `timescale`.
![image](https://user-images.githubusercontent.com/13324159/167747951-dfd263b6-b537-4e35-9992-1e850c5aaff9.png)

2022-05-11 04:48 UTC, ccbrown commented on mpeg2/src/temi.rs
> +    pub media_timestamp: u64,
Hmm... It seems like it would still be reasonable to omit `has_timestamp` from the struct. I can't imagine a user of the library ever wanting to use a 64 bit timestamp when 32 bits is enough or ever wanting to know whether a timestamp was encoded as 32 or 64 bits. But in the interest of being un-opinionated, I suppose leaving it is fine too.

I'll just make one ask here then: Either define some constants for `has_timestamp`'s possible values or make it an `enum` type (e.g. with `None`, `ThirtyTwoBits`, `SixtyFourBits`, and `Reserved` variants).

2022-05-11 18:47 UTC, ccbrown requested changes

2022-05-11 18:47 UTC, ccbrown commented on mpeg2/src/temi.rs
> +#[repr(C)]
Are these necessary?

```suggestion
```

2022-05-11 18:47 UTC, ccbrown commented on mpeg2/src/temi.rs
> +    pub fn encode_len(&self) -> usize {
In `AdaptationField`, this function is named "encoded_len". We should do the same here:

```suggestion
    pub fn encoded_len(&self) -> usize {
```

2022-05-11 18:47 UTC, ccbrown commented on mpeg2/src/temi.rs
> +    pub has_timecode: TimestampLength,
You should make a separate enum type for this, since the timecode is either 24 or 64 bits (not 32 or 64 like the timestamp).

```suggestion
    pub has_timecode: TimecodeLength,
```

2022-05-11 18:47 UTC, ccbrown commented on mpeg2/src/temi.rs
> +            buf[ret + 3] = self.duration as _;
```suggestion
            BigEndian::write_u16(&mut buf[ret..], self.frames_per_tc_seconds & 0x7fff);
            BigEndian::write_u16(&mut buf[ret + 2..], self.duration);
            if self.drop {
                buf[ret] |= 0b1000_0000;
            }
```

2022-05-11 18:47 UTC, ccbrown commented on mpeg2/src/temi.rs
> +            BigEndian::write_u64(&mut buf[ret..(ret + 8)], ptp_ts as u64);
These write ranges don't need to have an end specified. I would recommend just removing them:

```suggestion
            BigEndian::write_u64(&mut buf[ret..], ptp_ts as u64);
```

Makes the code easier to read and check.

2022-05-11 18:47 UTC, ccbrown commented on mpeg2/src/temi.rs
> +        Ok(buf.len())
We have a variable named `ret`. We should either return it or name it something else like "offset".

```suggestion
        Ok(ret)
```

2022-05-11 18:47 UTC, ccbrown commented on mpeg2/src/ts.rs
> +            paused: true,
I think later in that test file, after about 10 seconds, the timeline unpauses, and you should start seeing actual timestamps. Can you check and see if you can find some TEMIs with actual, non-zero timestamps that we can add tests for?

2022-05-11 18:47 UTC, ccbrown commented on mpeg2/src/ts.rs
> +        }
Don't we also need to add 2 bytes for `adaptation_field_extension_length` and the flags after it?

```suggestion
        }
        if !self.temi_timeline_descriptors.is_empty() {
                len += 2;
        }
```

2022-05-11 18:47 UTC, ccbrown commented on mpeg2/src/ts.rs
> +                let transport_private_date_length = buf[n];
Typo:

```suggestion
                let transport_private_data_length = buf[n];
```

2022-05-11 18:47 UTC, ccbrown commented on mpeg2/src/ts.rs
> +            let mut n = if af.program_clock_reference_27mhz.is_some() { 8 } else { 2 };
We also need to skip additional bytes if the OPCR is present:

```suggestion
            if buf[1] & 0x08 != 0 {
                        n += 6; // skip over the OPCR
            }            
```

2022-05-11 18:47 UTC, ccbrown commented on mpeg2/src/ts.rs
> +                let transport_private_date_length = buf[n];
Can we add some length checks? Before we read from `buf[n]`, let's make sure buf is long enough. This function shouldn't panic on invalid input.

2022-05-11 18:47 UTC, ccbrown commented on mpeg2/src/ts.rs
> +                n += 2;
We need to check the LTW, piecewise rate, and seamless splice flags, and skip over additional bytes if any of those are non-zero.

2022-05-11 18:52 UTC, lzuosym commented on mpeg2/src/temi.rs
> +#[repr(C)]
No! they are not. will remove them.

2022-05-11 18:52 UTC, lzuosym commented on mpeg2/src/temi.rs
> +    pub fn encode_len(&self) -> usize {
👍

2022-05-11 18:55 UTC, lzuosym commented on mpeg2/src/temi.rs
> +    pub has_timecode: TimestampLength,
`TimestampLength` enum is used by both `has_timecode` and `has_timestamp`, maybe rename this enum to `TimeLength`?

2022-05-11 18:57 UTC, lzuosym commented on mpeg2/src/temi.rs
> +            buf[ret + 3] = self.duration as _;
Ah. this is much cleaner! 👍

2022-05-11 18:58 UTC, lzuosym commented on mpeg2/src/temi.rs
> +            BigEndian::write_u64(&mut buf[ret..(ret + 8)], ptp_ts as u64);
will remove all the redundant end indexes.

2022-05-11 19:02 UTC, lzuosym commented on mpeg2/src/temi.rs
> +        Ok(buf.len())
they're equal, should simplify return `ret`.

2022-05-11 19:05 UTC, lzuosym commented on mpeg2/src/ts.rs
> +            paused: true,
I don't see any `ntp_timestamp` or `ptp_timestamp` values set in those 2 test files.

2022-05-11 19:12 UTC, lzuosym commented on mpeg2/src/ts.rs
> +            let mut n = if af.program_clock_reference_27mhz.is_some() { 8 } else { 2 };
okay. I think we also need to skip `splice_countdown` if its flag is 1

2022-05-11 19:16 UTC, lzuosym commented on mpeg2/src/ts.rs
> +                let transport_private_date_length = buf[n];
The length was missed. will add them.

2022-05-11 20:32 UTC, ccbrown commented on mpeg2/src/temi.rs
> +    pub has_timecode: TimestampLength,
My point is that it shouldn't be used for both of them. Because the timecode is either 24 bits or 64 bits, but the timestamp is either 32 or 64 bits. They don't have the same possible lengths.

2022-05-11 22:08 UTC, lzuosym commented on mpeg2/src/temi.rs
> +    pub has_timecode: TimestampLength,
I see you point, maybe we can define the `enum` as follows,
```rust
pub enum TimeFieldLength {
    None = 0,
    Short = 1,
    Long = 2,
}
```
Then it makes sense to be used by both of them. `Short` means length is less than or equal to 32 bits.

2022-05-11 22:17 UTC, ccbrown commented on mpeg2/src/temi.rs
> +    pub has_timecode: TimestampLength,
🤷‍♂️ Either works.

2022-05-11 23:58 UTC, ccbrown requested changes
I'm seeing a few more issues. Btw when the structures get as complex as this, I find it really helps to try to make the code look like the spec as much as possible. We've done a really good job of this in the h264 crate for example: https://github.com/sportsball-ai/av-rs/blob/main/h264/src/sequence_parameter_set.rs

It might be worth using some sort of bitstream reader like we do there so you can just write code like:

```
let adaptation_field_length = bitstream.read_u8()?;
if (adaptation_field_length > 0) {
    let discontinuity_indicator = bitstream.read_bit()?;
    let random_access_indicator = bitstream.read_bit()?;
    let elementary_stream_priority_indicator = bitstream.read_bit()?;
    let pcr_flag = bitstream.read_bit()?;
    let opcr_flag = bitstream.read_bit()?;

    ...

    if opcr_flag {
        bitstream.skip_bytes(6)?;
    }    
    if splicing_point_flag {
        bitstream.skip_bytes(1)?;
    }    
}
```

Then we can get rid of a large amount of the math and be able to verify correctness at a glance.

2022-05-11 23:58 UTC, ccbrown commented on mpeg2/src/temi.rs
> +            _ => return Err(DecodeError::new("incorrect has_timecode")),
A value of 3 is reserved:

> The term "reserved", when used in the clauses defining the coded bit stream, indicates that the value may be used in the future for ISO defined extensions.

If we want to avoid breakage in the future, we should interpret things exactly how the spec says. Meaning, if this is 3, we should parse the drop, frames_per_tc_seconds, and duration fields, but not parse any timecode.

Same for timestamp.

2022-05-11 23:58 UTC, ccbrown commented on mpeg2/src/ts.rs
> +                            // Other types of TEMI descriptors are ignored
```suggestion
                            // Other types of AF descriptors are ignored
```

2022-05-11 23:58 UTC, ccbrown commented on mpeg2/src/temi.rs
> +                BigEndian::write_u64(&mut buf[9..17], self.media_timestamp);
```suggestion
            BigEndian::write_u32(&mut buf[5..], self.timescale);
            if self.has_timestamp == TimeFieldLength::Short {
                BigEndian::write_u32(&mut buf[9..], self.media_timestamp as u32);
                ret += 8;
            } else if self.has_timestamp == TimeFieldLength::Long {
                BigEndian::write_u64(&mut buf[9..], self.media_timestamp);
```

2022-05-11 23:58 UTC, ccbrown commented on mpeg2/src/temi.rs
> +                ret.media_timestamp = BigEndian::read_u64(&buf[9..17]);
```suggestion
            ret.timescale = BigEndian::read_u32(&buf[5..]);
            if ret.has_timestamp == TimeFieldLength::Short {
                ret.media_timestamp = BigEndian::read_u32(&buf[9..]) as u64;
                n += 8;
            } else {
                ret.media_timestamp = BigEndian::read_u64(&buf[9..]);
```

2022-05-11 23:58 UTC, ccbrown commented on mpeg2/src/ts.rs
> +                n += transport_private_data_length as usize + 1
```suggestion
                if n >= buf.len() || buf[n] as usize + n + 1 > buf.len() {
                    return Err(DecodeError::new("transport private data length too long"));
                }
                let transport_private_data_length = buf[n] as usize;
                af.private_data_types = buf[n..(n + transport_private_data_length)].to_vec();
                n += transport_private_data_length + 1
```

2022-05-11 23:58 UTC, ccbrown commented on mpeg2/src/ts.rs
> +                    return Err(DecodeError::new("adaptation field length too long"));
```suggestion
                    return Err(DecodeError::new("adaptation field too short for adaptation field extension"));
```

I want to make sure that if we see one of these errors, we can find out where it actually came from. Ideally no two error messages are the same.

2022-05-11 23:58 UTC, ccbrown commented on mpeg2/src/ts.rs
> +                if n + 2 > buf.len() {
> The adaptation_field_length is an 8-bit field specifying the number of bytes in the adaptation_field immediately following the adaptation_field_length. The value '0' is for inserting a single stuffing byte in the adaptation field of a transport stream packet.

It looks like it's valid for the adaptation field extension to be only 1 byte.

2022-05-11 23:58 UTC, ccbrown commented on mpeg2/src/ts.rs
> +                let temi_descriptors_len = buf[n] - 1;
`buf[n]` is the `adaptation_field_extension_length` field, which includes the bytes required by the fields we skip below.

Let's change this variable so that it's clear that this is the length of the adaptation field extension and not just those descriptors:

```suggestion
                let adaptation_field_extension_length = buf[n];
```

Then fix the size of the buffer below.

2022-05-12 00:35 UTC, lzuosym commented on mpeg2/src/temi.rs
> +                BigEndian::write_u64(&mut buf[9..17], self.media_timestamp);
still missed a lot  :disappointed:

2022-05-12 00:36 UTC, lzuosym commented on mpeg2/src/ts.rs
> +                    return Err(DecodeError::new("adaptation field length too long"));
Absolutely! 👍

2022-05-12 00:59 UTC, lzuosym commented on mpeg2/src/ts.rs
> +                if n + 2 > buf.len() {
Interesting!  I don't see the single stuffing byte when `adaptation_field_length` is '0' in the pseudo code implementation. 
![image](https://user-images.githubusercontent.com/13324159/167970165-d14f5b63-795d-424f-82f7-afe86aa7df70.png)

So for decode, if the `adaptation_field_length` is 0, we need to skip 1 byte in the `buf`
```
    pub fn decode(buf: &[u8]) -> Result<Self, DecodeError> {
        let mut af = Self::default();
        let af_length = buf[0];
        if af_length as usize > buf.len() - 1 {
            return Err(DecodeError::new("adaptation field length too long"));
        } else if buf[0] > 0 {
```

2022-05-12 01:03 UTC, lzuosym commented on mpeg2/src/ts.rs
> +                let temi_descriptors_len = buf[n] - 1;
> I'm seeing a few more issues. Btw when the structures get as complex as this, I find it really helps to try to make the code look like the spec as much as possible. We've done a really good job of this in the h264 crate for example: https://github.com/sportsball-ai/av-rs/blob/main/h264/src/sequence_parameter_set.rs
> 
> It might be worth using some sort of bitstream reader like we do there so you can just write code like:
> 
> ```
> let adaptation_field_length = bitstream.read_u8()?;
> if (adaptation_field_length > 0) {
>     let discontinuity_indicator = bitstream.read_bit()?;
>     let random_access_indicator = bitstream.read_bit()?;
>     let elementary_stream_priority_indicator = bitstream.read_bit()?;
>     let pcr_flag = bitstream.read_bit()?;
>     let opcr_flag = bitstream.read_bit()?;
> 
>     ...
> 
>     if opcr_flag {
>         bitstream.skip_bytes(6)?;
>     }    
>     if splicing_point_flag {
>         bitstream.skip_bytes(1)?;
>     }    
> }
> ```
> 
> Then we can get rid of a large amount of the math and be able to verify correctness at a glance.

Hmm, this looks much nicer! I'll talk a look at h264 create, and try to make semi crate similar.

2022-05-12 01:14 UTC, ccbrown commented on mpeg2/src/ts.rs
> +                if n + 2 > buf.len() {
You know what... I read this wrong. I thought I was looking at the spec for `adaptation_field_extension_length`. I don't think anything needs to change here.

2022-05-17 01:08 UTC, ccbrown requested changes

2022-05-17 01:08 UTC, ccbrown commented on mpeg2/src/ts.rs
> +                    let mut af_descr_bitstream = bs.wrapped_stream(adaptation_field_extension_length as usize - 1);
`adaptation_field_extension_length` is the length of the adaptation field, including the LTW, piecewise rate, and seamless splice fields. So this wouldn't be right if those were present.

I think you should just shadow `bs` as soon as you read `adaptation_field_extension_length`:

```rust
let adaptation_field_extension_length = bs.read_u8();
let bs = bs.wrapped_stream(adaptation_field_extension_length as usize);
```

2022-05-17 01:08 UTC, ccbrown commented on mpeg2/src/ts.rs
> +            af.random_access_indicator = Some(bs.read_boolean());
What would you think about making the `read_` methods return `Result` types so they could bubble up an error if there aren't enough bytes remaining? We could give them a `name` parameter so they could still provide meaningful errors:

```suggestion
            af.discontinuity_indicator = Some(bs.read_boolean("discontinuity_indicator")?);
            af.random_access_indicator = Some(bs.read_boolean("random_access_indicator")?);
```

This would allow us to get rid of the length checks from this function entirely and be a much more foolproof way to make sure it never panics.

2022-05-17 01:08 UTC, ccbrown commented on mpeg2/src/temi.rs
> +    pub fn encode(&self, bs: &mut BitstreamWriter) -> Result<usize, EncodeError> {
It might be kind of nice to make `Bitstream` an implementation detail instead of a public API:

```suggestion
    pub fn encode(&self, buf: &[u8]) -> Result<usize, EncodeError> {
        let bs = Bitstream::new(buf);
```

2022-05-17 04:12 UTC, lzuosym commented on mpeg2/src/ts.rs
> +                    let mut af_descr_bitstream = bs.wrapped_stream(adaptation_field_extension_length as usize - 1);
Ahh, great catch! 👍

2022-05-17 04:28 UTC, lzuosym commented on mpeg2/src/ts.rs
> +            af.random_access_indicator = Some(bs.read_boolean());
I haven't got used to idiomatic way to handle errors in Rust. will update the PR.

2022-05-17 20:51 UTC, ccbrown requested changes
This is soo easy to review now! A few things.

2022-05-17 20:51 UTC, ccbrown commented on mpeg2/src/temi.rs
> +
I'm not sure if this is correct, but it's not necessary anymore right?

```suggestion
```

2022-05-17 20:51 UTC, ccbrown commented on mpeg2/src/temi.rs
> +
No need for this now, right?

```suggestion
```

2022-05-17 20:51 UTC, ccbrown commented on mpeg2/src/ts.rs
> +                af.private_data_types = bs.read_n_bytes(transport_private_data_length as usize, "private_data_types")?.to_vec();
Typo maybe? Was this meant to be "bytes"?

```suggestion
                af.private_data_bytes = bs.read_n_bytes(transport_private_data_length as usize, "private_data_bytes")?.to_vec();
```

2022-05-17 22:02 UTC, lzuosym commented on mpeg2/src/temi.rs
> +
yep, we don't need this check.

2022-05-17 22:03 UTC, lzuosym commented on mpeg2/src/temi.rs
> +
same

2022-05-17 22:03 UTC, lzuosym commented on mpeg2/src/ts.rs
> +                af.private_data_types = bs.read_n_bytes(transport_private_data_length as usize, "private_data_types")?.to_vec();
it's a typo!

2022-05-17 23:14 UTC, ccbrown approved these changes

2022-05-17 23:38 UTC, merged