add api for avs-agent to embed wall-clock timestamps
sportsball-ai/av-rs pull request #92
Opened 2022-05-19 16:35 UTC by lzuosym

2022-05-19 16:42 UTC, lzuosym commented on mpeg2/src/pes.rs
> +                temi_timeline_descriptors: Cow::Borrowed(&self.config.temi),
@ccbrown `temi` info is shared by all `ts:Packet`s produced by `pes::Packet`, there is not need to duplicate `temi` for `ts::Packet`, but I couldn't find a way to pass Rust lifetime check.

2022-05-19 23:18 UTC, lzuosym commented on mpeg2/src/pes.rs
> +                temi_timeline_descriptors: Cow::Borrowed(&self.config.temi),
Thanks! I made simple things complicated!

2022-05-20 16:48 UTC, ccbrown commented on mpeg2/src/pes.rs
> +    pub temi: Option<Vec<TEMITimelineDescriptor>>,
Is there any difference in behavior between `None` and `Some(vec![])`? Why not just make this a `Vec`?

```suggestion
    pub temi: Vec<TEMITimelineDescriptor>,
```

2022-05-20 16:48 UTC, ccbrown commented on mpeg2/src/ts.rs
> +    pub temi_timeline_descriptors: Option<Vec<TEMITimelineDescriptor>>,
Same question.

2022-05-20 16:57 UTC, ccbrown commented on mpeg2/src/pes.rs
> +    pub temi: Option<Vec<TEMITimelineDescriptor>>,
Also, for consistency:

```suggestion
    pub temi_timeline_descriptors: Vec<TEMITimelineDescriptor>,
```

2022-05-20 16:57 UTC, lzuosym commented on mpeg2/src/pes.rs
> +    pub temi: Option<Vec<TEMITimelineDescriptor>>,
By using `Option`, we can simply call `take()` to move the temi vectors into AdaptationField, all the following would be `None`.  
```rust
fn next(&mut self) -> Option<Self::Item> {
    let adaptation_field = self.header.map(|header| {
        let mut af = ts::AdaptationField {
            random_access_indicator: if self.config.random_access_indicator { Some(true) } else { None },
            temi_timeline_descriptors: self.config.temi.take(),
```

2022-05-20 16:59 UTC, lzuosym commented on mpeg2/src/ts.rs
> +    pub temi_timeline_descriptors: Option<Vec<TEMITimelineDescriptor>>,
it can be removed.

2022-05-20 17:01 UTC, lzuosym commented on mpeg2/src/pes.rs
> +    pub temi: Option<Vec<TEMITimelineDescriptor>>,
just lazy, but should make it consistent

2022-05-20 17:04 UTC, ccbrown requested changes

2022-05-20 17:04 UTC, ccbrown commented on mpeg2/src/pes.rs
> +    pub temi: Option<Vec<TEMITimelineDescriptor>>,
Let's try to avoid a leaky abstraction here. The implementation details of that function shouldn't dictate what the public API looks like.

There are a few ways you can do the same thing without making this an `Option`. For example, you could `mem::swap` it with an empty `Vec`.

2022-05-20 17:06 UTC, lzuosym commented on mpeg2/src/pes.rs
> +    pub temi: Option<Vec<TEMITimelineDescriptor>>,
Oh, okay, let me check the `mem::swap` method.

2022-05-20 19:55 UTC, ccbrown requested changes
Naming suggestion. Otherwise, this looks good to me!

2022-05-20 19:55 UTC, ccbrown commented on mpeg2/src/muxer.rs
> +    pub temi: Vec<TEMITimelineDescriptor>,
I'm always a fan of spelling things out fully in `pub` APIs:

```suggestion
    pub temi_timeline_descriptor: Vec<TEMITimelineDescriptor>,
```

2022-05-20 20:02 UTC, lzuosym commented on mpeg2/src/muxer.rs
> +    pub temi: Vec<TEMITimelineDescriptor>,
will keep that in mind!!!!

2022-05-20 20:13 UTC, ccbrown approved these changes

2022-05-20 20:16 UTC, merged